name: CICD

on: push

jobs:
  cicd:
      name: cicd
      runs-on: ubuntu-latest
      steps:
        - name: Check code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
            
        - name: Run Super-Linter
          uses: github/super-linter@v3.17.0
          env:
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt

        - name: Run unit tests
          run: |
           pip install pytest pytest-cov
           pytest test_calculator.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

        - name: Login to Docker
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags,labels) for docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with: 
            images: cicdmt001/cicd_v1.0

        - name: Build and Push Docker image  
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: user/app:latest
        #    labels: ${{ steps.meta.outputs.labels }}
        #- name: Build and Push Docker Image
          #run: |
           #echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "cicdmt001" --password-stdin
           #docker image build -t cicdmt001/cicd_v1.0:v1
           #docker push cicdmt001/cicd_v1.0:v1
          #uses: mr-smithers-excellent/docker-build-push@v4
          #with:
            #image: cicdmt001/cicd_v1.0
            #registry: docker.io
            #username: ${{ secrets.DOCKER_USERNAME }}
            #password: ${{ secrets.DOCKER_PASSWORD }}
